ec-europa/europa-component-library

framework/index.scss, framework/organisms/footers/README.md, framework/organisms/footers/_footers.scss, framework/organisms/footers/footers.config.js, framework/organisms/footers/footers.html, framework/organisms/footers/package.json
The alignment is not perfect, as the following is not present in the overall build just yet:
```css
ul.list-inline > li {
display: inline-block;
}
```
=> feat(footers): add pattern

framework/index.scss, framework/molecules/notifications/README.md, framework/molecules/notifications/_notifications.scss, framework/molecules/notifications/notifications.config.js, framework/molecules/notifications/notifications.html, framework/molecules/notifications/package.json, package.json
=> feat(notifications): add notifications component

.stylelintrc, .stylelintrc.js, framework/atoms/labels/_labels.scss, package.json, yarn.lock
BEM Linting:
Add `@define nameofyourcomponent` in your scss file to turn on the linting of your file
=> chore(bem): check bem syntax

contributing.json
I hope it fixes the fact the gitmagic doesn't catch the JIRA issue in the title
=> fix(gitmagic): fix rules - no issue

framework/_partials/_preview.html, framework/organisms/site-headers/default/default.config.js, framework/organisms/site-headers/default/default.html, framework/organisms/site-headers/homepage/homepage.config.js, framework/organisms/site-headers/homepage/homepage.html
This PR makes use of [context in preview layouts](http://fractal.build/guide/components/preview-layouts#context-in-preview-layouts) in order to provide a kind of global context
=> feat(header): add global context - no issue

package.json, yarn.lock
Closes #96
https://greenkeeper.io/
=> chore(package): update webdriverio to version 4.7.1 - no issue

docs/coding-conventions/javascript.md, docs/coding-conventions/scss.md
Any typo? Missing information?
=> docs(qa): initiate qa docs - INNO-506

framework/components/ecl-meta/package.json, framework/components/ecl-page-headers/package.json
Ready packages to be published.
=> chore(deps): publish ready packages - noissue

fractal.js
=> fix(colors): use the same colors as in the color palette - INNO-596

package.json, yarn.lock
=> chore(deps): update dependencies - no issue

framework/components/ecl-messages/README.md
=> feat(messages): update doc - INNO-655

framework/components/ecl-rss-links/README.md
=> feat(rss-links): update doc - INNO-656

framework/components/ecl-labels/package.json
=> chore(package): fix wrong name and version - no issue

framework/layout/ecl-listings/ecl-listings.config.js
=> fix(listings): hide listings - INNO-738

framework/content/ecl-typography/ecl-typography-fonts/README.md, framework/content/ecl-typography/ecl-typography-headings/README.md, framework/content/ecl-typography/ecl-typography-paragraphs/README.md
=> docs(typography): replace "EC Dark Grey" by "EC Grey" - INNO-745

framework/components/ecl-page-headers/README.md
=> docs(navigation-menus): update README.md - noissue

framework/components/ecl-navigation/ecl-navigation-menus/_horizontal-menus.scss
=> fix(nav-menu): enhance contrast ratio of the toggle - no issue

framework/components/ecl-footers/README.md
=> docs(footer): documentation update - INNO-853

framework/components/ecl-tables/README.md
=> docs(readme): update README.md - INNO-852

framework/components/ecl-lang-select-sites/ecl-lang-select-sites.config.js, framework/components/ecl-lang-select-sites/ecl-lang-select-sites.twig, framework/components/ecl-language-list/ecl-language-list.config.js, framework/components/ecl-language-list/ecl-language-list.twig
=> fix(language-list): remove icon and empty classes - INNO-901

framework/components/ecl-datepickers/README.md
Potentially adds Pikaday in the ECL release. For the moment, it adds documentation only.
=> docs(datepicker): explain Pikaday dependency and give examples - INNO-940

README.md
Deploy docs of the old v0.24.0 branch
=> chore(deploy): deploy previous branch - INNO-1087

README.md, netlify.toml
Re-deploy the v0 branch's website to netlify
=> chore(publish): republish v0 - no issue

docs/04-documentation.md
=> doc(how to): fix links

src/systems/ec/specs/components/blockquote/docs/usage.md, src/systems/eu/specs/components/blockquote/docs/usage.md
=> feat(content): update usage blockquote - no issue

src/website/src/pages/ec/index.md
=> ECL components EC introduction page

src/website/src/pages/eu/index.md
=> Introduction of ECL (EU)

src/website/src/pages/ec/index.md
add applications to justify the use of Europa
=> docs: update introduction

src/website/src/pages/eu/index.md
to add applications to justify the use of Europa
=> docs: update EU introduction page

src/website/src/pages/index.md
for this page to justify the name Europa
=> docs: add application

src/website/src/pages/ec/resources/eui/eui.md
=> docs: add content for eUI

src/systems/ec/specs/components/hero-banner/docs/usage.md
This is the first commit of this content (just a wiki mirror)
=> docs(hero banner): version01

src/website/src/pages/ec/resources/eui/eui.md
=> docs(ec/eui): update eui.md - no issue

src/website/src/pages/index.md
=> docs(splash): add the political correct version

src/website/src/pages/eu/index.md
=> docs(eu/homepage): add official version

src/systems/ec/specs/components/site-header/docs/usage.md
=> docs:(ec/site-header): draft first version

src/systems/ec/specs/components/blockquote/docs/usage.md
=> docs(ec/blockquote): update

src/systems/ec/specs/components/blockquote/docs/usage.md
=> docs(ec/blockquote): update text

src/systems/ec/specs/components/footer/docs/usage.md
=> docs(ec/footer): add intro
